# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import sys
from PyQt6 import QtCore,  QtWidgets
from PyQt6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PyQt6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,QAction,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PyQt6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QHeaderView,
    QLabel, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QSplitter, QTreeWidget, QTreeWidgetItem, QVBoxLayout, QWidget)
from PyQt6.QtWebEngineWidgets import QWebEngineView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QSize(800, 600))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")


        self.folderSelectButton = QPushButton(self.centralwidget)
        self.folderSelectButton.setObjectName(u"folderSelectButton")
        self.horizontalLayout.addWidget(self.folderSelectButton)

        self.previousButton = QPushButton(self.centralwidget)
        self.previousButton.setObjectName(u"previousButton")
        self.horizontalLayout.addWidget(self.previousButton)

        self.nextButton = QPushButton(self.centralwidget)
        self.nextButton.setObjectName(u"nextButton")
        self.horizontalLayout.addWidget(self.nextButton)

        self.applyPreviousButton = QPushButton(self.centralwidget)
        self.applyPreviousButton.setObjectName(u"applyPreviousButton")
        self.horizontalLayout.addWidget(self.applyPreviousButton)

        self.SaveButton = QPushButton(self.centralwidget)
        self.SaveButton.setObjectName(u"SaveButton")
        self.horizontalLayout.addWidget(self.SaveButton)

        self.applyPrevSaveNext = QPushButton(self.centralwidget)
        self.applyPrevSaveNext.setObjectName(u"applyPrevSaveNext")
        self.horizontalLayout.addWidget(self.applyPrevSaveNext)
        
        self.applyToAllOutButton = QPushButton(self.centralwidget)
        self.applyToAllOutButton.setObjectName(u"applyToAllOutButton")
        self.horizontalLayout.addWidget(self.applyToAllOutButton)

        self.googleTakeOutButton = QPushButton(self.centralwidget)
        self.googleTakeOutButton.setObjectName(u"googleTakeOutButton")
        self.horizontalLayout.addWidget(self.googleTakeOutButton)

        self.clearGoogleTakeOutButton = QPushButton(self.centralwidget)
        self.clearGoogleTakeOutButton.setObjectName(u"clearGoogleTakeOutButton")
        self.horizontalLayout.addWidget(self.clearGoogleTakeOutButton)



        self.gridLayout.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")

        self.mainContentSplitter = QSplitter(self.centralwidget)
        self.mainContentSplitter.setObjectName(u"mainContentSplitter")
        self.mainContentSplitter.setOrientation(Qt.Orientation.Horizontal)
        self.mainContentSplitter.setChildrenCollapsible(False)

        self.fileListWidget = QTreeWidget(self.mainContentSplitter)
        self.fileListWidget.setObjectName(u"fileListWidget")
        self.fileListWidget.setMinimumSize(QSize(180, 0))
        self.fileListWidget.setColumnCount(3)
        __qtreewidgetitem1 = QTreeWidgetItem()
        __qtreewidgetitem1.setText(0, u"Name")
        __qtreewidgetitem1.setText(1, u"Latitude")
        __qtreewidgetitem1.setText(2, u"Longitude")
        self.fileListWidget.setHeaderItem(__qtreewidgetitem1)

        self.previewMapSplitter = QSplitter(self.mainContentSplitter)
        self.previewMapSplitter.setObjectName(u"previewMapSplitter")
        self.previewMapSplitter.setOrientation(Qt.Orientation.Vertical)
        self.previewMapSplitter.setChildrenCollapsible(False)

        self.imageViewWidget = QtWidgets.QLabel(parent=self.previewMapSplitter)
        self.imageViewWidget.setScaledContents(False)
        self.imageViewWidget.setMinimumSize(QSize(200, 150))
        self.imageViewWidget.setObjectName("imageViewWidget")
        self.imageViewWidget.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.mapViewWidget = QWebEngineView(parent=self.previewMapSplitter)
        self.create_mapHTLM()

        self.gpsFilesListWidget = QTreeWidget(self.mainContentSplitter)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"Takeout Files");
        self.gpsFilesListWidget.setHeaderItem(__qtreewidgetitem)
        self.gpsFilesListWidget.setObjectName(u"gpsFilesListWidget")
        self.gpsFilesListWidget.setMinimumSize(QSize(180, 0))

        self.mainContentSplitter.setSizes([240, 640, 220])
        self.previewMapSplitter.setSizes([320, 280])
        self.horizontalLayout_2.addWidget(self.mainContentSplitter)

        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 2, 1, 1)


        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")

        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName(u"Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
        # setupUi



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Photo Location Updater"))
        self.nextButton.setText(_translate("MainWindow", ">"))
        self.applyPreviousButton.setText(_translate("MainWindow", "Apply Previous"))
        self.folderSelectButton.setText(_translate("MainWindow", "Select Folder"))
        self.previousButton.setText(_translate("MainWindow", "<"))
        self.SaveButton.setText(_translate("MainWindow", "Save and next"))
        self.applyPrevSaveNext.setText(_translate("MainWindow", "Apply Prev, Save, Next"))    
        self.applyToAllOutButton.setText(_translate("MainWindow", u"Apply To All", None))    
        self.googleTakeOutButton.setText(_translate("MainWindow", u"Enable Google Takeout", None))
        self.clearGoogleTakeOutButton.setText(_translate("MainWindow", u"Disable Google Takeout", None))
        
        self.menuHelp.setTitle(QtCore.QCoreApplication.translate("MainWindow", u"Help", None))
        self.actionAbout.setText(QtCore.QCoreApplication.translate("MainWindow", u"About", None))
       

    def create_mapHTLM(self):
        """
        Creates an HTML template for a Leaflet map.
        Returns:
        str: The HTML template for the Leaflet map.
        """

        # Load the map.html file
        if hasattr(sys, '_MEIPASS'):
            map_path = os.path.join(sys._MEIPASS, 'map.html')
        else:
            map_path = 'map.html'


        with open(map_path, "r") as file:
            htmlFromFile = file.read()

        
        # Set the HTML content to the mapViewWidget
        self.mapViewWidget.setHtml(htmlFromFile)